admins/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('home', views.Home.as_view(), name='home'),
    path('base', views.Base.as_view(), name='base'),

    path('courses', views.AddCourse.as_view(), name='courses'),
    path('course/list', views.ListCourse.as_view(), name='listcourse'),
    path('batches', views.AddBatch.as_view(), name='batches'),
    path('batch/list', views.ListBatches.as_view(), name='listbatch'),
    path('addtelecaller', views.AddTelecaller.as_view(), name='telecalleradd'),
    path('telecaller/list', views.ListTelecallers.as_view(), name='listtelecallers'),
    path('course/delete/<int:pk>', views.CourseDelete.as_view(), name='coursedelete'),
    path('course/update/<int:pk>', views.CourseUpdate.as_view(), name='courseupdate'),
    path('telecaller/delete/<int:pk>', views.TelecallerDelete.as_view(), name='telecallerdelete'),
    path('telecaller/update/<int:pk>', views.TelecallerUpdate.as_view(), name='telecallerupdate'),
    path('batch/delete/<int:pk>', views.BatchDelete.as_view(), name='batchdelete'),
    path('batch/update/<int:pk>', views.BatchUpdate.as_view(), name='batchupdate'),

]

reportingsystem/urls.py
from django.contrib import admin
from django.urls import path, include

from authapp import views

urlpatterns = [

    path("", views.loghome, name='loghome'),
    path('admin/', admin.site.urls),
    path('admins/', include('admins.urls')),
    # path('drsystem/', include('drsystem.urls'))
    path('telecaller/', include('telecaller.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

telecaller/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('studentadd', views.StudentAdd.as_view(), name='studentadd'),
    path('telehome', views.TeleHome.as_view(), name='telehome'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX
    path('enquires/list', views.ListEnquires.as_view(), name='listenquires'),
    path('studupdate/<int:pk>', views.StudentUpdate.as_view(), name='studupdate'),
    path('studdelete/<int:pk>', views.StudentDelete.as_view(), name='studdelete'),

]

telecaller/models.py
from django.db import models

from admins.models import Course, Batch
from authapp.models import MyUser
from django.utils import timezone

class Student(models.Model):

    ADMITTED = 'admitted'
    NOT_INTERESTED = 'not_interested'
    FOLLOWUP = 'followup'
    options = (
        ('ADMITTED', 'admitted'),
        ('NOT_INTERESTED', 'not_interested'),
        ('FOLLOWUP', 'followup')
    )
    student_name = models.CharField(max_length=120)
    phone = models.IntegerField()
    email = models.EmailField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    batch = models.ForeignKey(Batch, on_delete=models.CASCADE)
    status = models.CharField(max_length=120, choices=options, default='FOLLOWUP')
    followup_date = models.DateField(null=True)
    enquiry_date = models.DateTimeField(default=timezone.now)
    telecaller = models.ForeignKey(MyUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.student_name

telecaller/forms.py
from django import forms

from admins.models import Course, Batch
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['student_name', 'phone', 'email', 'course', 'batch', 'status', 'followup_date', 'enquiry_date']

        widgets = {
            'student_name': forms.TextInput(attrs={'class':'form-control'}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            'course' : forms.Select(attrs={'class':'form-control'}),
            'batch': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            "followup_date": forms.DateInput(attrs={"type": "date"}),
            "enquiry_date": forms.DateInput(attrs={"type": "date"}),
            'phone': forms.NumberInput(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['batch'].queryset = Course.objects.none()

        if 'course' in self.data:
            try:
                course_id = int(self.data.get('course'))
                self.fields['batch'].queryset = Batch.objects.filter(course_id=course_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['batch'].queryset = self.instance.course.batch_set.order_by('batch_name')


class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['student_name', 'phone', 'email', 'course', 'batch', 'status', 'followup_date', 'enquiry_date']

        widgets = {
            'student_name': forms.TextInput(attrs={'class':'form-control'}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            'course' : forms.Select(attrs={'class':'form-control'}),
            'batch': forms.Select(attrs={'class': 'form-control'}),
            'status': forms.Select(attrs={'class': 'form-control'}),
            "followup_date": forms.DateInput(attrs={"type": "date"}),
            "enquiry_date": forms.DateInput(attrs={"type": "date"}),
            'phone': forms.NumberInput(attrs={"class": "form-control"}),
        }

telecaller/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import CreateView, TemplateView, ListView, UpdateView, DeleteView
from admins.models import Batch
from .forms import StudentForm, StudentUpdateForm
from .models import Student


class TeleHome(TemplateView):
    template_name = 'telecaller/telehome.html'


class StudentAdd(CreateView):
    model = Student
    template_name = 'telecaller/studentadd.html'
    form_class = StudentForm
    success_url = '/telecaller/studentadd'

    def form_valid(self, form):
        form.instance.telecaller = self.request.user
        if form.instance.status == 'ADMITTED':
            batch = Batch.objects.get(id=form.data.__getitem__('batch'))
            if batch.available_seat == 0:
                messages.error(self.request, 'SORRY!! No seat available for the selected course')
                return redirect('studentadd')
            else:
                batch.available_seat = batch.available_seat - 1
                batch.save()
        return super(StudentAdd, self).form_valid(form)


class StudentUpdate(UpdateView):
    model = Student
    form_class = StudentUpdateForm
    template_name = 'telecaller/studupdate.html'
    success_url = '/telecaller/listenquires'

    def form_valid(self, form):
        if form.instance.status == 'ADMITTED':
            batch = Batch.objects.get(id=form.data.__getitem__('batch'))
            if batch.available_seat == 0:
                messages.error(self.request, 'SORRY!! No seat available for the selected course')
                return redirect('studentadd')
            else:
                batch.available_seat = batch.available_seat - 1
                batch.save()
        return super(StudentUpdate, self).form_valid(form)



class StudentDelete(DeleteView):
    model = Student
    template_name = 'telecaller/delete.html'
    success_url = '/telecaller/listenquires'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # import pdb
        # pdb.set_trace()
        x = context['student']
        if x.status == 'ADMITTED':
            batch = Batch.objects.get(id=x.batch.id)
            batch.available_seat = batch.available_seat + 1
            batch.save()
        return context


def load_cities(request):
    course_id = request.GET.get('course_id')
    print(course_id)
    cities = Batch.objects.filter(course_id=course_id).all()
    print(cities)
    return render(request, 'telecaller/coursebatch.html', {'cities': cities})


class ListEnquires(ListView):
    model = Student
    template_name = 'telecaller/liststudents.html'
    context_object_name = 'students'

    def get_queryset(self):
        return Student.objects.filter(telecaller=self.request.user)

templates/telecaller/basetelecaller.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css"
          integrity="sha512-BnbUDfEUfV0Slx6TunuB042k9tuKe3xrD6q4mg5Ed72LTgzDIcLPxg6yI2gcMFRyomt+yJJxE+zJwNmxki6/RA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/fontawesome.min.css"
          integrity="sha512-U/gkPvaqpUI9k7UC1ivfLUO+hb1dPzQyWskzeYoDjZENrWvLVZ40mg510RvWsVP3YcuKW4lAkfxgU9khbNhTrg=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{%static 'css/styles.css'%}">
    <title>Document</title>
</head>
<body>


<nav class="navbar navbar-expand-lg navbarTransparent">
    <div class="container">
        <a class="navbar-brand" href="{%url 'home' %}"> Reporting System</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="#">
                        <i class="far  fa-user-circle icolor"></i>&nbsp;{{request.user}}
                    </a>
                </li>


                <li class="nav-item">
                    <a class="nav-link" href="{%url 'logout'%}"><i
                            class="fas fa-sign-out-alt icolor"></i>&nbsp;Logout</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid ">
    <div class="row">
        <div class="col-md-2 db-padd">
            <div class="dashbard-left">
                <div class="row">


                    <div class="col-md-12">
                        <div class="dashleft-2">
                            <ul class="list-group">
                                <li class="list-group-item "><a href="{%url 'studentadd'%}"><i
                                        class="fas fa-plus-square "></i>&nbsp;Add Student Enquires</a></li>

                                      <li class="list-group-item"><a href="{%url 'listenquires'%}"><i
                                        class="fas fa-list"></i>&nbsp;List Student Enquires</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-10">
            <!--------------------------------------->
            {%block body_block%}


            {%endblock%}
            <!--------------------------------------->
        </div>
    </div>

    <div class="footer mt-5">

        <h3>copyright</h3>

    </div>

</div>

</body>
</html>

templates/telecaller/coursebatch.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.batch_name }}</option>
{% endfor %}

templates/telecaller/deletestud.html
<!DOCTYPE html>

{%extends 'telecaller/basetelecaller.html'%}

{%load static%}


{% block body_block %}

<div class="mt-5 ms-5">


    <form action="" method="post">
        {%csrf_token%}
    <h3>Are you sure you want to delete {{name}}? </h3>

                <a class="btn btn-warning" href="{%url 'listenquires'%}">Cancel</a>

        <button class="btn btn-danger" type="submit">Delete</button>

    </form>
</div>
{% endblock %}

templates/telecaller/liststudents.html
<!DOCTYPE html>

{%extends 'telecaller/basetelecaller.html'%}

{%load static%}


{% block body_block %}
<table class="table">
    <tr>
        <th>student name</th>
        <th>phone</th>
        <th>email</th>
        <th>course</th>
        <th>batch</th>
        <th>status</th>
        <th>followup date</th>
        <th>enquiry date</th>
        <th>telecaller</th>
        <th>Actions</th>
    </tr>
    
    {%for student in students%}
    
    <tr>
        <td>{{student.student_name}}</td>
        <td>{{student.phone}}</td>
        <td>{{student.email}}</td>
        <td>{{student.course}}</td>
        <td>{{student.batch}}</td>
        <td>{{student.status}}</td>
        <td>{{student.followup_date}}</td>
        <td>{{student.enquiry_date}}</td>
        <td>{{student.telecaller.name}}</td>
        <td> <a href="{%url 'studupdate' student.pk%}" class="btn btn-secondary">Update</a>
                    <td> <a href="{%url 'studdelete' student.pk%}" class="btn btn-secondary">Delete</a>

</td>
    </tr>
    {%endfor%}
</table>
{%endblock%}

templates/telecaller/studentadd.html
<!DOCTYPE html>

{%extends 'telecaller/basetelecaller.html'%}

{%load static%}


{% block body_block %}
<div class="container">
    <div class="row">
        <center>
            {% if messages %}
            <div class="alert alert-success" style="width:500px; height:100px;">
                {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="mesage-alert-success">{{ message }}<i class="fas fa-check-circle"></i></div>
                {% endif %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="mesage-alert-danger">{{ message }}<i class="fas fa-times-circle"></i></div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
        </center>
    </div>

    <form method="post" id="StudentForm" data-cities-url="{% url 'ajax_load_cities' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_course").change(function () {
        const url = $("#StudentForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const courseId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'course_id': courseId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_batch").html(data);  // replace the contents of the city input with the data that came from the server
                /*
                let html_data = '<option value="">---------</option>';
                data.forEach(function (batch) {
                    html_data += `<option value="${batch.id}">${batch.batch_name}</option>`
                });
                console.log(html_data);
                $("#id_batch").html(html_data);
                */
            }
        });

    });


</script>

{%endblock%}

templates/telecaller/studupdate.html
<!DOCTYPE html>

{%extends 'telecaller/basetelecaller.html'%}

{%load static%}


{% block body_block %}
<div class="container">
    <div class="row">
        <center>
            {% if messages %}
            <div class="alert alert-success" style="width:500px; height:100px;">
                {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                <div class="mesage-alert-success">{{ message }}<i class="fas fa-check-circle"></i></div>
                {% endif %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                <div class="mesage-alert-danger">{{ message }}<i class="fas fa-times-circle"></i></div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
        </center>
    </div>

    <form method="post" id="StudentForm" data-cities-url="{% url 'ajax_load_cities' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_course").change(function () {
        const url = $("#StudentForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const courseId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'course_id': courseId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_batch").html(data);  // replace the contents of the city input with the data that came from the server
                /*
                let html_data = '<option value="">---------</option>';
                data.forEach(function (batch) {
                    html_data += `<option value="${batch.id}">${batch.batch_name}</option>`
                });
                console.log(html_data);
                $("#id_batch").html(html_data);
                */
            }
        });

    });


</script>

{%endblock%}

templates/telecaller/telehome.html
<!DOCTYPE html>

{%extends 'telecaller/basetelecaller.html'%}

{%load static%}


{% block body_block %}

<h1>welcome telecaller</h1>
<a href="{%url 'studentadd'%}">Add Enquires</a>

<a href="{%url 'listenquires'%}">View Enquires</a>

{%endblock%}